language: 
    python

python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    # travis is supported PyPy 
install:
    "python setup.py install"

script:
    - "python setup.py test"

